--
-- Table structure for table `WEBUTILS_USERS`
--

DROP TABLE IF EXISTS `WEBUTILS_USERS`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `WEBUTILS_USERS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `DISPLAY_NAME` varchar(500) COLLATE latin1_bin NOT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `USER_NAME` varchar(50) COLLATE latin1_bin DEFAULT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `BASE_ENT_TYPE` varchar(200) COLLATE latin1_bin DEFAULT NULL,
  `PASSWORD` varchar(500) COLLATE latin1_bin NOT NULL,
  `OWNER_ENT_TYPE` varchar(200) COLLATE latin1_bin DEFAULT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `BASE_ENT_ID` bigint(20) DEFAULT NULL,
  `OWNER_ENT_ID` bigint(20) DEFAULT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_WEBUTILS_USERS_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  UNIQUE KEY `UQ_USERENTITY_UQ_USERS_BASE_DET` (`BASE_ENT_TYPE`,`BASE_ENT_ID`),
  UNIQUE KEY `UQ_USERENTITY_UQ_USERS_OWNR_UNAME` (`SPACE_IDENTITY`,`USER_NAME`),
  KEY `FK_WEBUTILS_USERS_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_WEBUTILS_USERS_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `WEBUTILS_USERS_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_WEBUTILS_USERS_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_USERS_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `WEBUTILS_USERS`
--

LOCK TABLES `WEBUTILS_USERS` WRITE;
/*!40000 ALTER TABLE `WEBUTILS_USERS` DISABLE KEYS */;
INSERT INTO `WEBUTILS_USERS` VALUES (3,'',NULL,'Kranthi','2017-12-06 12:41:14.000000','akranthi@yukthitech.com',1,'2017-12-06 12:41:14.000000',NULL,'nRmUS+uzuXGAUecG+POhoOC3aG0xZvTb1my/u3Kb+a9+5ZwZi+SlAWOuJKwmK67A',NULL,'\0',NULL,NULL,NULL,'dummy1'),(4,'',NULL,'Kalyani','2017-12-06 12:41:14.000000','kalyani@yukthitech.com',1,'2017-12-06 12:41:14.000000',NULL,'nRmUS+uzuXGAUecG+POhoOC3aG0xZvTb1my/u3Kb+a9+5ZwZi+SlAWOuJKwmK67A',NULL,'\0',NULL,NULL,NULL,'dummy2');
/*!40000 ALTER TABLE `WEBUTILS_USERS` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `RECRUIT_CANDIDATE`
--

DROP TABLE IF EXISTS `RECRUIT_CANDIDATE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `RECRUIT_CANDIDATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `ADDRESS` varchar(500) COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `EXPERIENCE` int(11) NOT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `PHONE_NO` varchar(30) COLLATE latin1_bin NOT NULL,
  `CURRENT_CTC` int(11) NOT NULL,
  `NOTICE_PERIOD` int(11) NOT NULL,
  `SKILLS` varchar(500) COLLATE latin1_bin NOT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `NAME` varchar(200) COLLATE latin1_bin NOT NULL,
  `MAIL_ID` varchar(200) COLLATE latin1_bin DEFAULT NULL,
  `EXPECTED_CTC` int(11) NOT NULL,
  `STATUS` varchar(50) COLLATE latin1_bin NOT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_RECRUIT_CANDIDATE_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_RECRUIT_CANDIDATE_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_RECRUIT_CANDIDATE_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `RECRUIT_CANDIDATE_IDX_CANDIDATEENTITY_EXPERIENCE` (`EXPERIENCE`),
  KEY `RECRUIT_CANDIDATE_IDX_CANDIDATEENTITY_MAILID` (`MAIL_ID`),
  KEY `RECRUIT_CANDIDATE_IDX_CANDIDATEENTITY_PHONENO` (`PHONE_NO`),
  KEY `RECRUIT_CANDIDATE_IDX_CANDIDATEENTITY_SKILLS` (`SKILLS`),
  KEY `RECRUIT_CANDIDATE_IDX_CANDIDATEENTITY_STATUS` (`STATUS`),
  KEY `RECRUIT_CANDIDATE_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_RECRUIT_CANDIDATE_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_RECRUIT_CANDIDATE_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `RECRUIT_CANDIDATE`
--

LOCK TABLES `RECRUIT_CANDIDATE` WRITE;
/*!40000 ALTER TABLE `RECRUIT_CANDIDATE` DISABLE KEYS */;
/*!40000 ALTER TABLE `RECRUIT_CANDIDATE` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `RECRUIT_EMPLOYER`
--

DROP TABLE IF EXISTS `RECRUIT_EMPLOYER`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `RECRUIT_EMPLOYER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `ADDRESS` varchar(500) COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `ALT_PHONE_NO` varchar(30) COLLATE latin1_bin DEFAULT NULL,
  `POC_NAME` varchar(200) COLLATE latin1_bin NOT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `POC_PHONE_NO` varchar(30) COLLATE latin1_bin NOT NULL,
  `NAME` varchar(200) COLLATE latin1_bin NOT NULL,
  `REG_DATE` datetime(6) NOT NULL,
  `POC_MAIL_ID` varchar(200) COLLATE latin1_bin DEFAULT NULL,
  `STATUS` varchar(50) COLLATE latin1_bin DEFAULT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_RECRUIT_EMPLOYER_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_RECRUIT_EMPLOYER_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_RECRUIT_EMPLOYER_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `RECRUIT_EMPLOYER_IDX_EMPLOYERENTITY_POCMAILID` (`POC_MAIL_ID`),
  KEY `RECRUIT_EMPLOYER_IDX_EMPLOYERENTITY_POCNAME` (`POC_NAME`),
  KEY `RECRUIT_EMPLOYER_IDX_EMPLOYERENTITY_POCPHONENO` (`POC_PHONE_NO`),
  KEY `RECRUIT_EMPLOYER_IDX_EMPLOYERENTITY_STATUS` (`STATUS`),
  KEY `RECRUIT_EMPLOYER_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_RECRUIT_EMPLOYER_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_RECRUIT_EMPLOYER_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `RECRUIT_EMPLOYER`
--

LOCK TABLES `RECRUIT_EMPLOYER` WRITE;
/*!40000 ALTER TABLE `RECRUIT_EMPLOYER` DISABLE KEYS */;
/*!40000 ALTER TABLE `RECRUIT_EMPLOYER` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `RECRUIT_JOB_OPENING`
--

DROP TABLE IF EXISTS `RECRUIT_JOB_OPENING`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `RECRUIT_JOB_OPENING` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MAX_CTC` int(11) NOT NULL,
  `REQ_CANDIDATE_COUNT` int(11) NOT NULL,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `JOB_PROFILE` varchar(1000) COLLATE latin1_bin NOT NULL,
  `SKILLS_REQUIRED` varchar(1000) COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `TITLE` varchar(500) COLLATE latin1_bin NOT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `EXP_REQUIRED` int(11) NOT NULL,
  `EMPLOYER_ID` bigint(20) NOT NULL,
  `MIN_CTC` int(11) NOT NULL,
  `EXTRA_DETAILS` varchar(1000) COLLATE latin1_bin DEFAULT NULL,
  `STATUS` varchar(255) COLLATE latin1_bin NOT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_RECRUIT_JOB_OPENING_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_RECRUIT_JOB_OPENING_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_RECRUIT_JOB_OPENING_EMPLOYER_ID` (`EMPLOYER_ID`),
  KEY `FK_RECRUIT_JOB_OPENING_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `RECRUIT_JOB_OPENING_IDX_JOBOPENINGENTITY_TITLE` (`TITLE`),
  KEY `RECRUIT_JOB_OPENING_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_RECRUIT_JOB_OPENING_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_RECRUIT_JOB_OPENING_EMPLOYER_ID` FOREIGN KEY (`EMPLOYER_ID`) REFERENCES `RECRUIT_EMPLOYER` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_RECRUIT_JOB_OPENING_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `RECRUIT_JOB_OPENING`
--

LOCK TABLES `RECRUIT_JOB_OPENING` WRITE;
/*!40000 ALTER TABLE `RECRUIT_JOB_OPENING` DISABLE KEYS */;
/*!40000 ALTER TABLE `RECRUIT_JOB_OPENING` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `RECRUIT_USER_ROLE`
--

DROP TABLE IF EXISTS `RECRUIT_USER_ROLE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `RECRUIT_USER_ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROLE` varchar(255) COLLATE latin1_bin NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_RECRUIT_USER_ROLE_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_RECRUIT_USER_ROLE_USER_ID` (`USER_ID`),
  CONSTRAINT `FK_RECRUIT_USER_ROLE_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `RECRUIT_USER_ROLE`
--

LOCK TABLES `RECRUIT_USER_ROLE` WRITE;
/*!40000 ALTER TABLE `RECRUIT_USER_ROLE` DISABLE KEYS */;
INSERT INTO `RECRUIT_USER_ROLE` VALUES (1,'ADMIN',3,'DUMMY-1'),(2,'ADMIN',4,'DUMMY-2');
/*!40000 ALTER TABLE `RECRUIT_USER_ROLE` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `WEBUTILS_ENTITY_EXTENSIONS`
--

DROP TABLE IF EXISTS `WEBUTILS_ENTITY_EXTENSIONS`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `WEBUTILS_ENTITY_EXTENSIONS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `OWNER_ENTITY_TYPE` varchar(100) COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `TARGET_ENTITY_TYPE` varchar(250) COLLATE latin1_bin NOT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `NAME` varchar(250) COLLATE latin1_bin NOT NULL,
  `CUSTOM_ATTR` varchar(2000) COLLATE latin1_bin DEFAULT NULL,
  `OWNER_ENTITY_ID` bigint(20) NOT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_EXTENSIONENTITY_NAME` (`SPACE_IDENTITY`,`NAME`),
  UNIQUE KEY `UQ_EXTENSIONENTITY_TARGET_OWNER` (`TARGET_ENTITY_TYPE`,`OWNER_ENTITY_TYPE`,`OWNER_ENTITY_ID`),
  UNIQUE KEY `UQ_WEBUTILS_ENTITY_EXTENSIONS_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_WEBUTILS_ENTITY_EXTENSIONS_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_WEBUTILS_ENTITY_EXTENSIONS_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `WEBUTILS_ENTITY_EXTENSIONS_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_WEBUTILS_ENTITY_EXTENSIONS_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_ENTITY_EXTENSIONS_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `WEBUTILS_ENTITY_EXTENSIONS`
--

LOCK TABLES `WEBUTILS_ENTITY_EXTENSIONS` WRITE;
/*!40000 ALTER TABLE `WEBUTILS_ENTITY_EXTENSIONS` DISABLE KEYS */;
/*!40000 ALTER TABLE `WEBUTILS_ENTITY_EXTENSIONS` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `WEBUTILS_EXTENSION_FIELDS`
--

DROP TABLE IF EXISTS `WEBUTILS_EXTENSION_FIELDS`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `WEBUTILS_EXTENSION_FIELDS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `EXTENSION_ID` bigint(20) NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `DESCRIPTION` varchar(500) COLLATE latin1_bin DEFAULT NULL,
  `LABEL` varchar(50) COLLATE latin1_bin NOT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `DATA_TYPE` varchar(50) COLLATE latin1_bin DEFAULT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `IS_REQUIRED` bit(1) DEFAULT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `NAME` varchar(50) COLLATE latin1_bin NOT NULL,
  `LOV_OPTIONS` varchar(2000) COLLATE latin1_bin DEFAULT NULL,
  `MAX_LENGTH` int(11) DEFAULT NULL,
  `EXT_COL_NAME` varchar(50) COLLATE latin1_bin NOT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_EXTENSIONFIELDENTITY_EXT_ID_COL_NAME` (`EXTENSION_ID`,`EXT_COL_NAME`),
  UNIQUE KEY `UQ_EXTENSIONFIELDENTITY_EXT_ID_LABEL` (`EXTENSION_ID`,`LABEL`),
  UNIQUE KEY `UQ_EXTENSIONFIELDENTITY_EXT_ID_NAME` (`EXTENSION_ID`,`NAME`),
  UNIQUE KEY `UQ_WEBUTILS_EXTENSION_FIELDS_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_WEBUTILS_EXTENSION_FIELDS_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_WEBUTILS_EXTENSION_FIELDS_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `WEBUTILS_EXTENSION_FIELDS_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_WEBUTILS_EXTENSION_FIELDS_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_EXTENSION_FIELDS_EXTENSION_ID` FOREIGN KEY (`EXTENSION_ID`) REFERENCES `WEBUTILS_ENTITY_EXTENSIONS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_EXTENSION_FIELDS_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `WEBUTILS_EXTENSION_FIELDS`
--

LOCK TABLES `WEBUTILS_EXTENSION_FIELDS` WRITE;
/*!40000 ALTER TABLE `WEBUTILS_EXTENSION_FIELDS` DISABLE KEYS */;
/*!40000 ALTER TABLE `WEBUTILS_EXTENSION_FIELDS` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `WEBUTILS_FILE_ENTITY`
--

DROP TABLE IF EXISTS `WEBUTILS_FILE_ENTITY`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `WEBUTILS_FILE_ENTITY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `FILE_NAME` varchar(500) COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `OWNER_ENTITY_FIELD` varchar(200) COLLATE latin1_bin NOT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `SIZE_IN_MB` bigint(20) NOT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `CUSTOM_ATT2` varchar(100) COLLATE latin1_bin DEFAULT NULL,
  `CUSTOM_ATT1` varchar(100) COLLATE latin1_bin DEFAULT NULL,
  `FILE` longblob NOT NULL,
  `OWNER_ENTITY_TYPE` varchar(250) COLLATE latin1_bin NOT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `OWNER_ENTITY_ID` bigint(20) NOT NULL,
  `CONTENT_TYPE` varchar(200) COLLATE latin1_bin DEFAULT NULL,
  `CUSTOM_ATT5` varchar(100) COLLATE latin1_bin DEFAULT NULL,
  `CUSTOM_ATT4` varchar(100) COLLATE latin1_bin DEFAULT NULL,
  `CUSTOM_ATT3` varchar(100) COLLATE latin1_bin DEFAULT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_WEBUTILS_FILE_ENTITY_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_WEBUTILS_FILE_ENTITY_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_WEBUTILS_FILE_ENTITY_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `WEBUTILS_FILE_ENTITY_FILE_OWNER_IDX` (`OWNER_ENTITY_TYPE`,`OWNER_ENTITY_ID`),
  KEY `WEBUTILS_FILE_ENTITY_IDX_FILEENTITY_CUSTOMATTRIBUTE1` (`CUSTOM_ATT1`),
  KEY `WEBUTILS_FILE_ENTITY_IDX_FILEENTITY_CUSTOMATTRIBUTE2` (`CUSTOM_ATT2`),
  KEY `WEBUTILS_FILE_ENTITY_IDX_FILEENTITY_CUSTOMATTRIBUTE3` (`CUSTOM_ATT3`),
  KEY `WEBUTILS_FILE_ENTITY_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_WEBUTILS_FILE_ENTITY_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_FILE_ENTITY_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `WEBUTILS_FILE_ENTITY`
--

LOCK TABLES `WEBUTILS_FILE_ENTITY` WRITE;
/*!40000 ALTER TABLE `WEBUTILS_FILE_ENTITY` DISABLE KEYS */;
/*!40000 ALTER TABLE `WEBUTILS_FILE_ENTITY` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `WEBUTILS_MAIL_TEMPLATE`
--

DROP TABLE IF EXISTS `WEBUTILS_MAIL_TEMPLATE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `WEBUTILS_MAIL_TEMPLATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `CONTENT_TEMPLATE` longtext COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `CUSTOMIZATION` longtext COLLATE latin1_bin,
  `CC_TEMPLATE` varchar(1000) COLLATE latin1_bin DEFAULT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `OWNER_ENTITY_TYPE` varchar(250) COLLATE latin1_bin NOT NULL,
  `BCC_TEMPLATE` varchar(1000) COLLATE latin1_bin DEFAULT NULL,
  `NAME` varchar(100) COLLATE latin1_bin NOT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `SUBJECT_TEMPLATE` varchar(2000) COLLATE latin1_bin NOT NULL,
  `OWNER_ENTITY_ID` bigint(20) NOT NULL,
  `TO_TEMPLATE` varchar(1000) COLLATE latin1_bin DEFAULT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_MAILTEMPLATEENTITY_TEMPLATE_NAME` (`NAME`,`OWNER_ENTITY_TYPE`,`OWNER_ENTITY_ID`),
  UNIQUE KEY `UQ_WEBUTILS_MAIL_TEMPLATE_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_WEBUTILS_MAIL_TEMPLATE_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_WEBUTILS_MAIL_TEMPLATE_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `WEBUTILS_MAIL_TEMPLATE_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_WEBUTILS_MAIL_TEMPLATE_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_MAIL_TEMPLATE_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `WEBUTILS_MAIL_TEMPLATE`
--

LOCK TABLES `WEBUTILS_MAIL_TEMPLATE` WRITE;
/*!40000 ALTER TABLE `WEBUTILS_MAIL_TEMPLATE` DISABLE KEYS */;
/*!40000 ALTER TABLE `WEBUTILS_MAIL_TEMPLATE` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `WEBUTILS_SEARCH_SETTINGS`
--

DROP TABLE IF EXISTS `WEBUTILS_SEARCH_SETTINGS`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `WEBUTILS_SEARCH_SETTINGS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `SEARCH_COLUMNS` varchar(4000) COLLATE latin1_bin NOT NULL,
  `PAGE_SIZE` int(11) NOT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `SEARCH_QUERY_NAME` varchar(100) COLLATE latin1_bin NOT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_SEARCHSETTINGSENTITY_UQ_USER_QUERY_NAME` (`USER_ID`,`SEARCH_QUERY_NAME`),
  UNIQUE KEY `UQ_WEBUTILS_SEARCH_SETTINGS_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_WEBUTILS_SEARCH_SETTINGS_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_WEBUTILS_SEARCH_SETTINGS_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `WEBUTILS_SEARCH_SETTINGS_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_WEBUTILS_SEARCH_SETTINGS_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_SEARCH_SETTINGS_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_SEARCH_SETTINGS_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `WEBUTILS_SEARCH_SETTINGS`
--

LOCK TABLES `WEBUTILS_SEARCH_SETTINGS` WRITE;
/*!40000 ALTER TABLE `WEBUTILS_SEARCH_SETTINGS` DISABLE KEYS */;
/*!40000 ALTER TABLE `WEBUTILS_SEARCH_SETTINGS` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `WEBUTILS_USER_NOTIFICATION`
--

DROP TABLE IF EXISTS `WEBUTILS_USER_NOTIFICATION`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `WEBUTILS_USER_NOTIFICATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `NOTIFICATION_TYPE` varchar(255) COLLATE latin1_bin NOT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `ENABLED` bit(1) NOT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_USERNOTIFICATIONENTITY_USER_NOTIFICATION` (`USER_ID`,`NOTIFICATION_TYPE`),
  UNIQUE KEY `UQ_WEBUTILS_USER_NOTIFICATION_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_WEBUTILS_USER_NOTIFICATION_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_WEBUTILS_USER_NOTIFICATION_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `WEBUTILS_USER_NOTIFICATION_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_WEBUTILS_USER_NOTIFICATION_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_USER_NOTIFICATION_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_USER_NOTIFICATION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `WEBUTILS_USER_NOTIFICATION`
--

LOCK TABLES `WEBUTILS_USER_NOTIFICATION` WRITE;
/*!40000 ALTER TABLE `WEBUTILS_USER_NOTIFICATION` DISABLE KEYS */;
/*!40000 ALTER TABLE `WEBUTILS_USER_NOTIFICATION` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `WEBUTILS_USER_ROLES`
--

DROP TABLE IF EXISTS `WEBUTILS_USER_ROLES`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `WEBUTILS_USER_ROLES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OWNER_TYPE` varchar(250) COLLATE latin1_bin NOT NULL,
  `SPACE_IDENTITY` varchar(150) COLLATE latin1_bin NOT NULL,
  `ROLE` varchar(200) COLLATE latin1_bin NOT NULL,
  `UPDATED_BY_ID` bigint(20) DEFAULT NULL,
  `CREATED_BY_ID` bigint(20) DEFAULT NULL,
  `UPDATED_ON` datetime(6) NOT NULL,
  `OWNER_ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `VERSION` int(11) NOT NULL,
  `CREATED_ON` datetime(6) NOT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_USERROLEENTITY_UQ_UROLE_ROLE` (`USER_ID`,`ROLE`,`OWNER_TYPE`,`OWNER_ID`),
  UNIQUE KEY `UQ_WEBUTILS_USER_ROLES_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `FK_WEBUTILS_USER_ROLES_CREATED_BY_ID` (`CREATED_BY_ID`),
  KEY `FK_WEBUTILS_USER_ROLES_UPDATED_BY_ID` (`UPDATED_BY_ID`),
  KEY `WEBUTILS_USER_ROLES_SPACE_IDENTITY_IDX` (`SPACE_IDENTITY`),
  CONSTRAINT `FK_WEBUTILS_USER_ROLES_CREATED_BY_ID` FOREIGN KEY (`CREATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_USER_ROLES_UPDATED_BY_ID` FOREIGN KEY (`UPDATED_BY_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WEBUTILS_USER_ROLES_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `WEBUTILS_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `WEBUTILS_USER_ROLES`
--

LOCK TABLES `WEBUTILS_USER_ROLES` WRITE;
/*!40000 ALTER TABLE `WEBUTILS_USER_ROLES` DISABLE KEYS */;
/*!40000 ALTER TABLE `WEBUTILS_USER_ROLES` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `WEBUTILS_USER_SESSION`
--

DROP TABLE IF EXISTS `WEBUTILS_USER_SESSION`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `WEBUTILS_USER_SESSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LAST_ACCESSED_ON` datetime(6) DEFAULT NULL,
  `SESSION_TOKEN` varchar(500) COLLATE latin1_bin NOT NULL,
  `USER_DETAILS` varchar(2000) COLLATE latin1_bin NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `CREATED_ON` datetime(6) DEFAULT NULL,
  `UQ_ENTITY_ID` varchar(100) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_WEBUTILS_USER_SESSION_UQ_ENTITY_ID` (`UQ_ENTITY_ID`),
  KEY `WEBUTILS_USER_SESSION_SESSION_TOKEN` (`SESSION_TOKEN`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;


