/*
 * The MIT License (MIT)
 * Copyright (c) 2015 "Yukthi Techsoft Pvt. Ltd." (http://yukthi-tech.co.in)

 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.yukthi.webutils.common.models;

/**
 * Login Response object
 * 
 * @author akiran
 */
public class LoginResponse extends BaseResponse
{
	/**
	 * Authorization token generated by server, that can be used for future requests.
	 */
	private String authToken;
	
	/**
	 * Instantiates a new login response.
	 */
	public LoginResponse()
	{}

	/**
	 * Instantiates a new login response.
	 *
	 * @param authToken the auth token
	 */
	public LoginResponse(String authToken)
	{
		this.authToken = authToken;
	}
	
	/**
	 * Instantiates a new login response.
	 *
	 * @param code the code
	 * @param message the message
	 */
	public LoginResponse(int code, String message)
	{
		super(code, message);
	}

	/**
	 * Gets the authorization token generated by server, that can be used for future requests.
	 *
	 * @return the authorization token generated by server, that can be used for future requests
	 */
	public String getAuthToken()
	{
		return authToken;
	}

	/**
	 * Sets the authorization token generated by server, that can be used for future requests.
	 *
	 * @param authToken the new authorization token generated by server, that can be used for future requests
	 */
	public void setAuthToken(String authToken)
	{
		this.authToken = authToken;
	}

}
